### ISSUE TITLE
I'm really frustrated. . .

### ISSUE THREAD

**Issue by AIMusicExperiment** [ltdrdata/ComfyUI-Inspire-Pack#9]
The mediapipe face detector of SEGs was working perfectly for me as of the 10th of September. Then both you and Fannovel16 updated you packs, now I can't get it to detect the face part correctly no matter what I do. I tried to revert to an earlier commit, but unfortunately, evidently I'm not smart enough to make that work.  Can you look into weather this can be made to work as it was when you first made it? Thanks!

**Comment by ltdrdata** [comment]
Update both ControlNet Auxiliary Preprocessors and Inspire/Impact Pact.

**Comment by AIMusicExperiment** [comment]
I updated both, and now it no longer finds the face. . .

**Comment by AIMusicExperiment** [comment]
It just seems to locate random squares

**Comment by ltdrdata** [comment]
> I updated both, and now it no longer finds the face. . .

Would you like to see how it comes out with just the Mediapipe preprocessor? The default resolution is 512.

**Comment by AIMusicExperiment** [comment]
I am literarily in tears, I had this working after all this time and now it won't work at all

**Comment by ltdrdata** [comment]
> It just seems to locate random squares
> 

Instead of the detector, try looking directly at the results from CAP's Mediapipe.

**Comment by AIMusicExperiment** [comment]
![ComfyUI_temp_htlfk_00007_](https://github.com/ltdrdata/ComfyUI-Inspire-Pack/assets/133187055/1949f824-75d6-47b9-a886-abb437c63449)
This is the output from Media Pipe

**Comment by ltdrdata** [comment]
> ![ComfyUI_temp_htlfk_00007_](https://user-images.githubusercontent.com/133187055/268475782-1949f824-75d6-47b9-a886-abb437c63449.png) This is the output from Media Pipe

And what is your original image's resolution?

**Comment by AIMusicExperiment** [comment]
1080X1080

**Comment by AIMusicExperiment** [comment]
![_00000](https://github.com/ltdrdata/ComfyUI-Inspire-Pack/assets/133187055/44cee9b2-3238-4594-86d9-74c08eae4ec8)

**Comment by ltdrdata** [comment]
> ![_00000](https://user-images.githubusercontent.com/133187055/268475905-44cee9b2-3238-4594-86d9-74c08eae4ec8.png)

Ok.. I'd reproduced issue.

**Comment by AIMusicExperiment** [comment]
Thank God I'm not stupid!

**Comment by AIMusicExperiment** [comment]
Sorry to be such an emotional boob, but I've worked really hard on this workflow. . .

**Comment by ltdrdata** [comment]
> Sorry to be such an emotional boob, but I've worked really hard on this workflow. . .

It's fixed now!

**Comment by AIMusicExperiment** [comment]
Thanks!

**Comment by AIMusicExperiment** [comment]
![detailer setings](https://github.com/ltdrdata/ComfyUI-Inspire-Pack/assets/133187055/18770dca-e141-4550-94d6-b79cfb53a883)
It still isn't working for me, these are the settings that worked before the update.  What Am I doing wrong?

**Comment by ltdrdata** [comment]
![workflow (3)](https://github.com/ltdrdata/ComfyUI-Inspire-Pack/assets/128333288/95c7f436-7588-4477-b763-df4554c010c4)

This image contains workflow.

**Comment by ltdrdata** [comment]
> ![detailer setings](https://user-images.githubusercontent.com/133187055/268477233-18770dca-e141-4550-94d6-b79cfb53a883.png) It still isn't working for me, these are the settings that worked before the update. What Am I doing wrong?

You should increase guide_size or check `force_inpaint`.

**Comment by AIMusicExperiment** [comment]
Okay, I have it working now, thanks for your excellent help!
